pipeline:

  publish:
    image: plugins/docker
    secrets: [docker_username, docker_password]
    settings:
      registry: git.oio.cat
      repo: git.oio.cat/albert/aacom
      tags: latest
      username: ${docker_username}
      password: ${docker_password}
    when:
      branch: ${CI_REPO_DEFAULT_BRANCH}
      event: push


  deploy:
    image: docker
    secrets: [docker_username, docker_password]
    commands:
      - pwd 
      - ls ./
      - docker login -u $docker_username -p $docker_password git.oio.cat
      - docker-compose up -d
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: ${CI_REPO_DEFATUL_BRANCH}
      event: push
